### ISSUE TITLE
Google Apps for Education

### ISSUE THREAD

**Issue by alemedeiros** [cacounicamp/Manual-do-Bixo#120]
Adicionar informações sobre o Drive infinito (provavelmente junto das informações de emails acadêmicos).

https://googleapps.unicamp.br

**Bônus:** Adicionar um *até a Unicamp* está tentando te obrigar a usar Gmail na seção "Tenha uma conta no Gmail!" ¯\\\_(ツ)_/¯
**Bônus++:** Se a pessoa tiver saco de colocar o emoji `¯\_(ツ)_/¯` junto desse texto.

**Comment by VFerrari** [comment]
Entao, nao tenho certeza se precisamos colocar isso, ate pq falam tudo isso na primeira aula de lab de 102 (pelo menos falaram pra mim)

**Comment by alemedeiros** [comment]
tudo isso o que? de usar gmail ou da existência do drive infinito?

e não acho que faz mal deixar essas informações, até porque temos várias informações sobre os emails acadêmicos que, querendo ou não, o pessoal sempre fala nas primeiras aulas de 102, mas ninguém entende / lembra. Querendo ou não é bom ter um lugar com isso registrado que a pessoa tenha visto em algum momento e possa voltar pra conferir depois.

mas isso não tem muita prioridade, anyway.
