### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by josenberg** [cacounicamp/Manual-do-Bixo#126]
O arquivo dessa url possui um link quebrado na seção do "Google Apps for Education". https://www.caco.ic.unicamp.br/manual.pdf

O problema é só uma typo na url, em vez de ser "http://http//bit.ly/2i8Lbbt" ele deveria ser "http*:*//http//bit.ly/2i8Lbbt";

Nesse repositorio o link esta correto, acho que precisa atualizar só o arquivo no servidor

**Comment by rmobis** [comment]
Complementando o report, todos os links em que foi usado `http://` no começo têm esse problema. O mesmo não acontece com os que usam `https://`. Provavelmente isso acontece pelo macro(?) `\url` já prefixar o endereço com `http://` enquanto `\urls` não o faz.

**Comment by rafaelsartori96** [comment]
Obrigado pelo aviso, resolverei isso após as provas. :)
