### ISSUE TITLE
Arte 2018

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#129]
Precisamos de uma arte para **capa** e **contra capa**. De preferência uma supimpa.

Posso tentar fazer uma nas férias, mas o deadline está próximo para meus dons de Photoshop, então se alguém tiver ideias prontas, comentem aqui.

**Comment by josenberg** [comment]
Arte já finalizada!
O que você acha?

![img_20171122_094125186](https://user-images.githubusercontent.com/3295383/33125900-966ab4be-cf69-11e7-8004-db1ccefa3956.jpg)

**Comment by rafaelsartori96** [comment]
Pelo visto não preciso mais fazer a arte, temos uma pronta

**Comment by VFerrari** [comment]
A arte de 2016 foi feita por nos mesmos, mas em 2017 por falta de "mao-de-obra qualificada" no CACo contratamos um artista (o mesmo que fez a estampa da nova camiseta), que devo dizer que fez um trabalho mto bom. O problema e que deu trabalho ficar falando com ele direcionando e aprovando/reprovando rascunhos.

**Comment by rafaelsartori96** [comment]
Tenho o Guia do Mochileiro da Galáxia aqui, posso tentar copiar depois, um a três dias de trabalho duro ficaria pronto.

**Comment by ablumers** [comment]
Oi Pessoal! Pra quando vcs precisam dessa arte?

**Comment by rafaelsartori96** [comment]
Até a primeira semana de 2018, se quiser colaborar, agradeceríamos muito :)

**Comment by rafaelsartori96** [comment]
![manual capa imagem](https://user-images.githubusercontent.com/1348868/34080670-fb84a12a-e328-11e7-9dde-2ecf777ba985.png)

Eu fiz uma arte caso @ablumers não pudesse, principalmente porque viajo dia 20 e minha atividade será bem reduzida. Se tiver duas artes, votamos a mais legal e deixamos a outra para o ano que vem, talvez.

**Comment by rafaelsartori96** [comment]
Vou fechar a _issue_ pois estamos próximos de terminar o manual. @ablumers se você tiver feito alguma arte (mesmo que seja apenas uma ideia), reabra e mostre aqui :) Ficaríamos bem felizes com uma ideia para o ano que vem (ou até para esse, se a ideia for mais original).
