### ISSUE TITLE
Adicionar cursos de línguas (CEL)

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#131]

**Comment by VFerrari** [comment]
Ja adicionei ano passado. Algumas coisas ja foram adicionadas e so nao mudaram no README

**Comment by henriquefacioli** [comment]
Alguém já está adicionando ao readme?

**Comment by rafaelsartori96** [comment]
Eu removi as pendências do README no pull request. Passei as coisas de lá para essas issues, se essa já existia, estava fechada.
