### ISSUE TITLE
Adicionar sistema PAD

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#132]

**Comment by VFerrari** [comment]
Ja tem, na secao "monitoria", so nao atualizamos o readme

**Comment by henriquefacioli** [comment]
Quem ficará encarregado de adicionar ao readme?

**Comment by rafaelsartori96** [comment]
Ok, vou fechar, já que já está no manual. Removi as pendências do README no _pull request_.
