### ISSUE TITLE
Adicionar descrição das modalidades AA/AB

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#134]
Fazer isso em uma parte que tenha relação com a engenharia, não vamos ficar misturando CC e EC ou passará a impressão do curso ser muito dividido (mais do que já é pelas modalidades).

Vale a pena dizer que um não exclui o outro: você pode ser os dois :)

**Comment by VFerrari** [comment]
Ja tinha uma issue disso, eh a ultima da pagina. Melhor fechar ou esta ou aquela, pra ficar uma so.

**Comment by rafaelsartori96** [comment]
Fecha aquela, eu li aquela mas na hora de transcrever o README não me toquei. Desculpe o duplicate.
