### ISSUE TITLE
Revisar seções das entidades

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#137]
O pedido às entidades foi enviado por e-mail e pelo Facebook dia 25/11/17.

Adicionar novidades, atualizar datas etc.

**Comment by rafaelsartori96** [comment]
Mandei novamente no email do IC e FEEC.

**Comment by henriquefacioli** [comment]
Close it?

**Comment by rafaelsartori96** [comment]
Pode ser, mas é algo anual de qualquer forma hahahahah
