### ISSUE TITLE
Correção de links do manual

### ISSUE THREAD

**Issue by henriquefacioli** [cacounicamp/Manual-do-Bixo#139]
É necessário revisar os links ativos do manual e encontrar quais estão online ou não e modificá-los. Olhando 5 minutos encontrei alguns:

[Basicamente todos os links da DAC]
Desistência de matrícula em disciplinas - bit.ly/1BcBsF4
Cancelamento de matrícula - bit.ly/1wQBGCq
Trancamento de matrícula - bit.ly/1xWO4SL
Proficiencia - bit.ly/1H3DhaS.

Poss ajudar a encontrar outros e corrigí-los em um futuro.

**Comment by rafaelsartori96** [comment]
Duplixada de #126, eu achei uma maneira de arrumar facilmente.

**Comment by VFerrari** [comment]
O site da DAC mudou este ano, entao todos que levam pra ele vao estar quebrados.
