### ISSUE TITLE
Atualizar RDs, coordenadores e outras coisas que mudam anualmente.

### ISSUE THREAD

**Issue by VFerrari** [cacounicamp/Manual-do-Bixo#141]
Olhando os ultimos commits vi algumas coisas que foram ajeitadas mas deveriam ser mudadas completamente. So um heads-up, isto e importante.

**Comment by rafaelsartori96** [comment]
Está marcado no meu manual físico pra alterar, deixei pra fazer depois das provas.

**Comment by rafaelsartori96** [comment]
Colocamos o e-mail que não foi confirmado se está correto (e que podemos utilizar), esquecemos o do Eric. A review foi falha, queria ensinar o Marcelo a usar git e acabei nem conferindo o código direito... Sinto muito, galera.

**Comment by rafaelsartori96** [comment]
Sou um péssimo code reviewer. Compilei o código e há quebra de várias linhas. Malditos emails grandes. `\email` e `\url` deveriam criar uma box para não quebrar a linha.
