### ISSUE TITLE
Pedir mensagem de boas-vindas para os diretores

### ISSUE THREAD

**Issue by VFerrari** [cacounicamp/Manual-do-Bixo#142]

**Comment by rafaelsartori96** [comment]
Já pedi a mensagem, aguardando resposta.

**Comment by rafaelsartori96** [comment]
Recebemos mensagem do IC, aguardo o da FEEC.

**Comment by rafaelsartori96** [comment]
Lembrei o diretor da FEEC, ele diz que ficará pronto até a primeira semana de 2018, sem falta.
