### ISSUE TITLE
Revisar estabelecimentos capitalistas

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#165]
É ano de eleição, vai dar PT? Para mostrar que o CACo é comunista, temos que revisar (adicionar novos, remover antigos, atualizar comentários) a seção de estabelecimentos comerciais.

**Comment by rafaelsartori96** [comment]
* Substituir pepeloco por yespeto
* Adicionar fruitlatte, açaí da barra, colorê em sorveterias

**Comment by lubp1** [comment]
Enquanto olho os links já estou confirmando endereços e telefones, mas ainda tem que atualizar as descrições e adicionar novos (pepe louco/yespeto, etc).

**Comment by rafaelsartori96** [comment]
@lubp1 Acredito que isso já tenha acabado aproximadamente, certo?
Você adicionou esses que comentei ou só reviu? Posso adicioná-los mais tarde.

**Comment by lubp1** [comment]
@rafaelsartori96 Falta adicionar esses, só atualizei os que estavam lá

**Comment by rafaelsartori96** [comment]
Colegas, se tiverem mais sugestões de lugares, me avisem.
