### ISSUE TITLE
Revisar nomes de representantes discentes e coordenadores, mensagem do diretor

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#166]
Temos que fazer isso no final do ano.

Temos de perguntar ao Rodolfo e ao diretor da FEEC se gostariam de atualizar a mensagem das unidades aos ingressantes.

**Comment by fbidu** [comment]
@rafaelsartori96 adiciona ele como 'assignee' na issue, fica mais fácil de acompanhar :D

**Comment by rafaelsartori96** [comment]
@fbidu Eu tentei, mas não entendi o critério do GitHub pois não aparece usuário algum quando digito o username do Carlos :/
