### ISSUE TITLE
Trancamento de matrícula em disciplina em férias de verão

### ISSUE THREAD

**Issue by rafaelsartori96** [cacounicamp/Manual-do-Bixo#181]
Chegou a pergunta à mim e enviei um e-mail à DAC. Criei a issue para comentar a resposta no manual, pois acho que a informação convém.

**Comment by fbidu** [comment]
Nossa, eu nem imaginava que isso fosse possível... Realmente, é relevante mesmo

**Comment by rafaelsartori96** [comment]
Recebi a resposta: **NÃO** há trancamento de disciplinas em período de férias.

**Comment by rafaelsartori96** [comment]
Vou fechar para continuar em #191, já que essa é uma issue específica contemplada pela outra.
