### ISSUE TITLE
Consertar links

### ISSUE THREAD

**Issue by VFerrari** [cacounicamp/Manual-do-Bixo#94]
**Imobiliarias:**
Imobiliaria Barao: imobiliariabarao.com
Lokal imoveis: lokalimoveis.com.br

**Restaurantes (alguns telefones):**
China in Box: chinainbox.com.br
Bardana: buffetbardana.com.br
Estancia Grill: Repetido, remover primeira ocorrencia
Barao das Pizzas: baraodaspizzas.com.br
Pizza Fiori: pizzafiori.com.br
Super Mega Pizza: link quebrado :(
Casa da Moqueca: casadamoqueca.com.br
Lanchao e Cia: lanchao.com.br
Sapore Pizza: saporepizzaria.com.br

**Bares, Lanchonetes e Restaurantes:**
Emporio do Nono: emporiodonono.com.br
La Salamandra: lasalamandratexmex.com.br
Solar dos Pampas: link quebrado :(
Estancia D'Oliveira: estanciadoliveira.com
Bar do Ze: link quebrado :(
Echos Studio Bar: echos.mus.br/studiobar

**Diversao**
Casa do Lago: www.casadolago.preac.unicamp.br/
Topazio Cinemas: pradoboulevard.com.br/cinema.asp
Teatro Amil (Antigo Teatro TIM): Virou Teatro Conteudo Teatral
Cooperativa Brasil: link quebrado :(
Campinas Hall: campinashall.com.br
Barril da Mafia: link quebrado :(
Shopping Jaragua: Fechou, remover

**Transporte**
Mural de caronas e UniCaronas: nope :(

**Outras Necessidades**
CPFL: cpfl.com.br
Sanasa: sanasa.com.br
Correios: correios.com.br
CNA: email - ciduniversitaria@cna.com.br (mudar), site - bit.ly/2i6iWM6
Wizard: email - cidadeuniversitaria@wizard.com.br
Paroquia Santa Isabel: liink quebrado :(
Posto Vo Joao: link quebrado :(

**Intercambio**
Ciencia Sem Fronteiras: remover?
Site da pro-reitoria de grad. sobre o CsF: nao existe mais...

**Grupos e Entidades da Unicamp**
DCE: link quebrado :(
ABU: abucampinas.blogspot.com.br (site desatualizado, 2014)
SECOMP: secomp.com.br

**Servicos da Unicamp**
Jornal da Unicamp: link quebrado :( (nao sei se ainda existe).

**Comment by Guilhermeslucas** [comment]
Estou arrumando os links! Mando o pull request em breve!

**Comment by Guilhermeslucas** [comment]
Como os sites que existiam de caronas acabaram, coloquei um comentário sobre grupos do Facebook!

**Comment by Guilhermeslucas** [comment]
CsF acho melhor retirar, enquanto o programa não voltar.

**Comment by Guilhermeslucas** [comment]
A descrição do CsF está boa, falando que existe a possibilidade de voltar e tal!

**Comment by Guilhermeslucas** [comment]
Done! Pode fechar quando aceitar o pull request! #101
