### ISSUE TITLE
Criar textos para ambas as modalidades da EC

### ISSUE THREAD

**Issue by VFerrari** [cacounicamp/Manual-do-Bixo#99]
Texto de introducao das modalidades ja esta feito.

**Comment by Guilhermeslucas** [comment]
Falta só colocar?

**Comment by Guilhermeslucas** [comment]
Esse texto já está escrito?

**Comment by VFerrari** [comment]
Só a introdução está pronta. Tentei fazer os textos de cada um ou pedir para alguem fazer, mas ninguém conseguiu

**Comment by VFerrari** [comment]
Adiado, nao vai ser possivel colocar no manual 017
